<?php
use Illuminate\Database\Seeder;


class FiltersDataTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('filters_data')->truncate();
        DB::table('filters_data')->insert(
            [
                [
                    'filter_id' => 'district',
                    'value' => 'Manhattan',
                    'parent_id' => '0',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'district',
                    'value' => 'Brooklyn',
                    'parent_id' => '0',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'district',
                    'value' => 'Queens',
                    'parent_id' => '0',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'district',
                    'value' => 'Bronx',
                    'parent_id' => '0',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'district',
                    'value' => 'Staten Island',
                    'parent_id' => '0',
                    'district_id' => '0',
                ],
                /*===================*/
                [
                    'filter_id' => 'type',
                    'value' => 'Condo',
                    'parent_id' => '0',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'type',
                    'value' => 'Co-Op',
                    'parent_id' => '0',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'type',
                    'value' => 'Town house',
                    'parent_id' => '0',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'type',
                    'value' => 'Multi family',
                    'parent_id' => '0',
                    'district_id' => '0',
                ],


                //========Manhattan===========
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'All Upper West Side',
                    'parent_id' => '1',
                    'district_id' => '1',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Lincoln Square',
                    'parent_id' => '1',
                    'district_id' => '1',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Morningside Heights',
                    'parent_id' => '1',
                    'district_id' => '1',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Upper West Side',
                    'parent_id' => '1',
                    'district_id' => '1',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'All Upper East Side',
                    'parent_id' => '1',
                    'district_id' => '2',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Carnegie Hill',
                    'parent_id' => '1',
                    'district_id' => '2',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Roosevelt Island',
                    'parent_id' => '1',
                    'district_id' => '2',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Upper East Side',
                    'parent_id' => '1',
                    'district_id' => '2',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'All Midtown',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Beekman',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Central Park South',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Clinton',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Fashion Center',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Hell\'s Kitchen',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Hudson Yards',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Kips Bay',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Chelsea',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Midtown',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Midtown South',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Midtown East',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Midtown West',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Murray Hill',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'NoMad',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Sutton Place',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Turtle Bay',
                    'parent_id' => '1',
                    'district_id' => '3',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'All Upper Manhattan',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'East Harlem',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Hamilton Heights',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Central Harlem',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Hudson Heights',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Manhattan Valley',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Upper Carnegie Hill',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Inwood',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Fort George',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Lenox Hill',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Manhattanville',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Washington Heights',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'West Harlem',
                    'parent_id' => '1',
                    'district_id' => '4',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Yorkville',
                    'parent_id' => '1',
                    'district_id' => '2',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'All Downtown',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Battery Park City',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Chelsea',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'East Village',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Financial District',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Flatiron',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Fulton/Seaport',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Gramercy Park',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Greenwich Village',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Little Italy',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Chinatown',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Civic Center',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Lower East Side',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Noho',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Soho',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Nolita',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Tribeca',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Two Bridges',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'West Village',
                    'parent_id' => '1',
                    'district_id' => '5',
                ],


                /*=========Brooklyn=========*/
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Greenpoint',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Williamsburg',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Downtown Brooklyn',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Fort Greene',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Brooklyn Heights',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Boerum Hill',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'DUMBO',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Vinegar Hill',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bedford-Stuyvesant',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Stuyvesant Heights',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Ocean Hill',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bushwick',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'East New York',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'New Lots',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'City Line',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Starrett City',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Red Hook',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Park Slope',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Gowanus',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Carroll Gardens',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Cobble Hill',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Sunset Park',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Windsor Terrace',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Crown Heights',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Weeksville',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Prospect Heights',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Columbia St Waterfront District',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Prospect Lefferts Gardens',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bay Ridge',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'DUMBO',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Fort Hamilton',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Dyker Heights',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bensonhurst',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bath Beach',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Gravesend',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Borough Park',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Mapleton',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Ocean Parkway',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Kensington',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Coney Island',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Brighton Beach',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Ditmas Park',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Fiske Terrace',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Seagate',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Flatbush',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Midwood',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Sheepshead Bay',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Homecrest',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Madison',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Manhattan Beach',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Brownsville',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Prospect Park South',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Northeast Flatbush',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Farragut',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Wingate',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Greenwood',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Canarsie',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Flatlands',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Marine Park',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Gerritsen Beach',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Mill Basin',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Old Mill Basin',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bergen Beach',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Clinton Hill',
                    'parent_id' => '2',
                    'district_id' => '0',
                ],


                /*========Queens===========*/
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Astoria',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Long Island City',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Hunters Point',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Sunnyside',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Woodside',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Jackson Heights',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'East Elmhurst',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'North Corona',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Elmhurst',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Corona',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Maspeth',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Middle Village',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Ridgewood',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Glendale',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Rego Park',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Forest Hills',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Flushing',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Whitestone',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Malba',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Beechhurst',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'College Point',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Fresh Meadows',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Kew Gardens Hills',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Jamaica Hills',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Woodhaven',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Richmond Hill',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Kew Gardens',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Howard Beach',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Hamilton Beach',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Ramblersville',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Rockwood Park',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Lindenwood',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Old Howard Beach',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Howard Park',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Ozone Park',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'South Ozone Park',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bayside',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bay Terrace (Queens)',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Douglaston',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Little Neck',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Auburndale',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Jamaica',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'South Jamaica',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Hollis',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'St. Albans',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Laurelton',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Cambria Heights',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Queens Village',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Glen Oaks Village',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Floral Park',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bellerose',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Rosedale',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Springfield Gardens',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Briarwood',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Jamaica Estates',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'New Hyde Park',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'South Richmond Hill',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Oakland Gardens',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Hillcrest',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Pomonok',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Utopia',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'East Flushing',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Murray Hill (Queens)',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bowne Park',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Clearview',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Ditmars-Steinway',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Alley Park',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Queensboro Hill',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Rockaway All',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Far Rockaway',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Broad Channel',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Arverne',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Rockaway Park',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bayswater',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Belle Harbor',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Breezy Point',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Neponsit',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Edgemere',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Hammels',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Brookville',
                    'parent_id' => '3',
                    'district_id' => '0',
                ],

                /*========Bronx===========*/
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Concourse',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Tremont',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'North New York',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Eastchester',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Mott Haven',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Wakefield',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'East Tremont',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Woodlawn',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Morrisania',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Baychester',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Riverdale',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Williamsbridge',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Belmont',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Laconia',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'University Heights',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Van Nest',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Crotona Park East',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bronxdale',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Schuylerville',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Pelham Parkway',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Fieldston',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Morris Park',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Kingsbridge Heights',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'City Island',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bedford Park',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bronxwood',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Westchester Village',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Pelham Bay',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Fordham',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Pelham Gardens',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Morris Heights',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Throgs Neck',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Highbridge',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Parkchester',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Country Club',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Castle Hill',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Longwood',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Soundview',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Melrose',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Woodstock',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Edenwald',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Spuyten Duyvil',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Norwood',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Kingsbridge',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Claremont',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Westchester Square',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'West Farms',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Hunts Point',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Marble Hill',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Locust Point',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Co-op City',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Mt. Hope',
                    'parent_id' => '4',
                    'district_id' => '0',
                ],

                /*=========Staten Island==================*/
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'North Shore',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Howland Hook',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Port Ivory',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Arlington',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Mariners Harbor',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Elm Park',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Manor Heights',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Port Richmond',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'West New Brighton',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'West Brighton',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Sunset Hill',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Livingston',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Snug Harbor',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Randall Manor',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'New Brighton',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Saint George',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Tompkinsville',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Brighton Heights',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Saint Pauls',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Stapleton',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Clifton',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Fox Hills',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Rosebank',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Shore Acres',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Park Hill',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Grymes Hill',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Stapleton Heights',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Ward Hill',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Silver Lake',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'East Shore',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Fort Wadsworth',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Arrochar',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Grasmere',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Emerson Hill',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'South Beach',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Old Town',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Ocean Breeze',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Dongan Hills',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Todt Hill',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Lower Todt Hill',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Grant City',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Midland Beach',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'New Dorp',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'New Dorp Beach',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Oakwood',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Oakwood Beach',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Lighthouse Hill',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'High Rock',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Richmondtown',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bay Terrace',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Egbertville',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Mid-Island',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Graniteville',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bulls Head',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Willowbrook',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'New Springville',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Clove Lakes',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Heartland Village',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'La Tourette',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Meiers Corners',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Westerleigh',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Castleton Corners',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Royal Oak',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Sunnyside',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'South Shore',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Greenridge',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Arden Heights',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Great Kills',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Eltingville',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Annadale',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Huguenot',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Huguenot Beach',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Princes Bay',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Pleasant Plains',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Woodrow',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Rossville',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Charleston',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Old Place',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Richmond Valley',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Mount Loretto',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Butler Manor',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Sandy Ground',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Tottenville',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Tottenville Beach',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'West Shore',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Bloomfield',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'The Teleport',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Chelsea (Staten Island)',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],
                [
                    'filter_id' => 'sub_districts',
                    'value' => 'Travis',
                    'parent_id' => '5',
                    'district_id' => '0',
                ],

            ]
        );

        $ammneties = array (
            0 => 'Bike Room',
            1 => 'Children\'s Playroom',
            2 => 'Concierge',
            3 => 'Gym',
            4 => 'Laundry in Building',
            5 => 'Live-in Super',
            6 => 'Media Room',
            7 => 'Package Room',
            8 => 'Swimming Pool',
            9 => 'Storage Available',
            10 => 'Roof Deck',
            11 => 'NYC Storm Zone 1',
            12 => 'Parking Available',
            13 => 'Valet',
            14 => 'Valet Parking',
            15 => 'Cold Storage',
            16 => 'Community Recreation Facilities',
            17 => 'Smoke-free',
            18 => 'Deck',
            19 => 'Garden',
            20 => 'Virtual Doorman',
            21 => 'Waterfront',
            22 => 'NYC Storm Zone 5',
            23 => 'NYC Storm Zone 4',
            24 => 'Hot Tub',
            25 => 'NYC Storm Zone 2',
            26 => 'Garage Parking',
            27 => 'Green Building',
            29 => 'NYC Storm Zone 3',
            30 => 'Patio',
            31 => 'NYC Storm Zone 6',
        );

        $insert = array();
        foreach ($ammneties as $amnetie){
            $insert[] =
                [
                    'filter_id' => 'filters',
                    'value' => $amnetie,
                    'parent_id' => '0',
                    'district_id' => '0',

                ];

        }

        DB::table('filters_data')->insert(
            $insert
        );
    }
}
